RegisterAndLogin/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^login/', include('login.urls', namespace='login')),
	url(r'^captcha/', include('captcha.urls')),
]

login/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Created by Flynn on 2018-02-03 21:40
from django.conf.urls import url
from . import views

app_name = 'login'
urlpatterns = [
	url(r'^index/$', views.index, name='index'),
	url(r'^login/$', views.login, name='login'),
	url(r'^register/$', views.register, name='register'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^confirm/$', views.user_confirm, name='confirm')
]

login/models.py
from django.db import models


class User(models.Model):
	gender = (
		('male', '男'),
		('female', '女'),
	)

	name = models.CharField(max_length=128, unique=True)
	password = models.CharField(max_length=256)
	email = models.EmailField(unique=True)
	sex = models.CharField(max_length=32, choices=gender, default='男')
	c_time = models.DateTimeField(auto_now_add=True)
	has_confirmed = models.BooleanField(default=False)

	def __str__(self):
		return self.name

	class Meta:
		ordering = ['-c_time']
		verbose_name = '用户'
		verbose_name_plural = '用户'


class ConfirmString(models.Model):
	code = models.CharField(max_length=256)
	user = models.OneToOneField('User')
	c_time = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.user.name + " " + self.code

	class Meta:
		ordering = ['-c_time']
		verbose_name = '确认码'
		verbose_name_plural = '确认码'

login/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Created by Flynn on 2018-02-04 0:01
from django import forms
from .models import User
from captcha.fields import CaptchaField
from captcha.fields import CaptchaField


class UserForm(forms.Form):
	username = forms.CharField(label='用户名', max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
	password = forms.CharField(label='密码', max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
	captcha = CaptchaField(label='验证码')


"""
class UserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['name', 'password']

	def __init__(self, *args, **kwargs):
		super(UserForm, self).__init__(*args, **kwargs)
		self.fields['name'].label = '用户名'
		self.fields['password'].label = '密码'
"""


class RegisterForm(forms.Form):
	gender = (
		('male', '男'),
		('female', '女'),
	)
	username = forms.CharField(label='用户名', max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
	password1 = forms.CharField(label='密码', max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
	password2 = forms.CharField(label='确认密码', max_length=256,
	                            widget=forms.PasswordInput(attrs={'class': 'form-control'}))
	email = forms.EmailField(label='邮箱地址', widget=forms.EmailInput(attrs={'class': 'form-control'}))
	sex = forms.ChoiceField(label='性别', choices=gender)
	captcha = CaptchaField(label='验证码')

login/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpRequest
from .models import User, ConfirmString
from .forms import UserForm, RegisterForm
import hashlib
import datetime
from RegisterAndLogin import settings


# Create your views here.

def index(request):
	return render(request, 'login/index.html')


# def login(request):
# 	if request.method == 'POST':
# 		username = request.POST.get('username')
# 		password = request.POST.get('password')
# 		message = '所有字段必须填写'
# 		if username and password:
# 			username = username.strip()
# 			password = password.strip()
# 			try:
# 				user = User.objects.get(name=username)
# 				print(user, user.password, sep='\t')
# 				if user.password == password:
# 					print('username={},password={}'.format(username, password))
# 					return HttpResponseRedirect(reverse('login:index'))
# 				else:
# 					message = '密码不正确'
# 			except:
# 				message = '用户名不存在'
# 		return render(request, 'login/login.html', {'message': message})
# 	return render(request, 'login/login.html')

def login(request):
	if request.session.get('is_login', None):
		return HttpResponseRedirect(reverse('login:index'))

	if request.method == 'POST':
		login_form = UserForm(request.POST)
		message = '请检查需要填写的内容'
		if login_form.is_valid():
			username = login_form.cleaned_data.get('username')
			password = login_form.cleaned_data.get('password')
			try:
				username = username.strip()
				user = User.objects.get(name=username)
				if not user.has_confirmed:
					message = '用户还未确认通过'
					return render(request, 'login/login.html', locals())
				if user.password == hash_code(password):
					request.session['is_login'] = True
					request.session['user_id'] = user.id
					request.session['user_name'] = user.name
					return HttpResponseRedirect(reverse('login:index'))
				else:
					message = '密码不正确'
			except:
				message = '用户不存在'
		return render(request, 'login/login.html', locals())

	login_form = UserForm()
	return render(request, 'login/login.html', locals())


def register(request):
	if request.session.get('is_login', None):
		return redirect('/login/index.html')

	if request.method == 'POST':
		register_form = RegisterForm(request.POST)
		message = '请检查填写的内容'
		if register_form.is_valid():
			username = register_form.cleaned_data.get('username')
			password1 = register_form.cleaned_data.get('password1')
			password2 = register_form.cleaned_data.get('password2')
			email = register_form.cleaned_data.get('email')
			sex = register_form.cleaned_data.get('sex')
			if password1 != password2:
				message = '两次输入密码不一致'
				return render(request, 'login/register.html', locals())
			else:
				same_name_user = User.objects.filter(name=username)
				if same_name_user:
					message = '用户名已存在，请重新填写用户名'
					return render(request, 'login/register.html', locals())
				same_email_user = User.objects.filter(email=email)
				if same_email_user:
					message = '该邮箱已被使用，请重新填写邮箱'
					return render(request, 'login/register.html', locals())

				new_user = User.objects.create()
				new_user.name = username
				new_user.password = hash_code(password1)
				new_user.email = email
				new_user.sex = sex
				new_user.save()

				code = make_confirm_string(new_user)
				send_email(email, code)
				message = '请前往邮箱进行确认'

				return redirect('/login/login/')
	register_form = RegisterForm()
	return render(request, 'login/register.html', locals())


def logout(request):
	# return redirect('/login/index/')
	if not request.session.get('is_login', None):
		return HttpResponseRedirect(reverse('login:index'))
	request.session.flush()
	return HttpResponseRedirect(reverse('login:index'))


def user_confirm(request):
	code = request.GET.get('code', None)
	message = ''

	print('code = {}'.format(code))

	try:
		confirm = ConfirmString.objects.get(code=code)
	except:
		message = '无效请求'
		return render(request, 'login/confirm.html', locals())

	c_time = confirm.c_time
	now = datetime.datetime.now()
	if now > c_time + datetime.timedelta(settings.CONFIRM_DAYS):
		confirm.user.delete()
		message = '您的邮件已过期，请重新注册'
		return render(request, 'login/confirm.html', locals())
	else:
		confirm.user.has_confirmed = True
		confirm.user.save()
		confirm.delete()
		message = '感些确认，请使用账户登录'
		return render(request, 'login/confirm.html', locals())


def hash_code(s, salt='RegisterAndLogin'):
	h = hashlib.sha256()
	s += salt
	h.update(s.encode())
	return h.hexdigest()


def make_confirm_string(user):
	now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
	code = hash_code(user.name, now)
	ConfirmString.objects.create(code=code, user=user)
	return code


def send_email(email, code):
	from django.core.mail import EmailMultiAlternatives
	subject = '来自flynngod@sina.com的注册确认邮件'
	text_content = '如果看到了该条消息，则说明不提供HTML链接功能'
	html_content = '<p><a href="http://{}/login/confirm/?code={}" target=blank>点击此链接完成注册，该链接有效期为{}天</a></p>'.format(
		'127.0.0.1:8000',
		code, settings.CONFIRM_DAYS)

	msg = EmailMultiAlternatives(subject, text_content, settings.EMAIL_HOST_USER, [email])
	msg.attach_alternative(html_content, 'text/html')
	msg.send()

login/templates/login/confirm.html
{% extends 'base.html' %}
{% block title %}注册确认{% endblock %}
{% block content %}
    <div class="row">
        <h1 class="text-center">{{ message }}</h1>
    </div>
    <script>
        window.setTimeout('window.location=\'{% url "login:login" %}\'')
    </script>
{% endblock content %}

login/templates/login/index.html
{% extends 'base.html' %}
{% block title %}主页{% endblock title %}
{% block content %}
    {% if request.session.is_login %}
        <h1>你好，欢迎回来，{{ request.session.user_name }}</h1>
    {% else %}
        <h1>你还未登录，只能访问公开内容</h1>
    {% endif %}
{% endblock content %}

login/templates/login/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}登录{% endblock title %}
{% block css %}
    <link href="{% static 'css/login.css' %}"/>
{% endblock css %}

{% block content %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
            <form class='form-login' action="{% url 'login:login' %}" method="post">
                {% csrf_token %}

                {% if message %}
                    <div class="alert alert-warning">{{ message }}</div>
                {% endif %}

                <h2 class="text-center">欢迎登录</h2>

                <div>
                    {{ login_form.username.label_tag }}
                    {{ login_form.username }}
                </div>
                <div>
                    {{ login_form.password.label_tag }}
                    {{ login_form.password }}
                </div>

                <div>
                    {{ login_form.captcha.errors }}
                    {{ login_form.captcha.label_tag }}
                    {{ login_form.captcha }}
                </div>

                <button type="reset" class="btn btn-default pull-left">重置</button>
                <button type="submit" class="btn btn-primary pull-right">提交</button>
            </form>
        </div>
    </div> <!-- /container -->
{% endblock %}

login/templates/login/register.html
{% extends 'base.html' %}
{% block title %}注册{% endblock %}

{% block content %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
            <form action="{% url 'login:register' %}" method="post">
                {% if message %}
                    <div class="alert alert-warning">{{ message }}</div>
                {% endif %}
                {% csrf_token %}

                <h2 class="text-center">欢迎注册</h2>

                <div class="form-group">
                    {{ register_form.username.label_tag }}
                    {{ register_form.username }}
                </div>

                <div class="form-group">
                    {{ register_form.password1.label_tag }}
                    {{ register_form.password1 }}
                </div>

                <div class="form-group">
                    {{ register_form.password2.label_tag }}
                    {{ register_form.password2 }}
                </div>

                <div class="form-group">
                    {{ register_form.email.label_tag }}
                    {{ register_form.email }}
                </div>

                <div class="form-group">
                    {{ register_form.sex.label_tag }}
                    {{ register_form.sex }}
                </div>

                <div class="form-group">
                    {{ register_form.captcha.errors }}
                    {{ register_form.captcha.label_tag }}
                    {{ register_form.captcha }}
                </div>

                <button type="reset" class="btn btn-default pull-left">重置</button>
                <button type="submit" class="btn btn-primary pull-right">注册</button>

            </form>
        </div>
    </div>
{% endblock content %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}base{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'dist/css/bootstrap.min.css' %}" rel="stylesheet">

    {% block css %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav"
                    aria-expanded="false">
                <span class="sr-only">切换导航条</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Mysite</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="my-nav">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'login:index' %}">主页</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.session.is_login %}
                    <li><a href="#">当前在线：{{ request.session.user_name }}</a></li>
                    <li><a href="{% url 'login:logout' %}">退出</a></li>
                {% else %}
                    <li><a href="{% url 'login:login' %}">登录</a></li>
                    <li><a href="{% url 'login:register' %}">注册</a></li>
                {% endif %}

            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

{% block content %}{% endblock %}


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'js/jquery-3.2.1.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'dist/js/bootstrap.min.js' %}"></script>
</body>
</html>